server:
  port: 8761
spring:
  application:
    name: Service Registry
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF