server:
  port: 8761
spring:
  application:
    name: service-registry
eureka:
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 20
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: "http://${eureka.instance.hostname}:${server.port}/eureka/"
logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF